platform: linux
image_resource:
  type: docker-image
  source:
    repository: odpks/pks-ci
run:
  path: git-pks-kubernetes-release-ci/ci/tasks/config-blobstore/task.sh
inputs:
  - name: git-pks-kubernetes-release
  - name: git-pks-kubernetes-windows-release
  - name: git-pks-kubernetes-release-ci
params:
  GCS_JSON_KEY: ((gcs-bosh-blobstore-json-key))
  