name: ((deployment-name))

releases:
  - name: kubo
    version: ((kubo-version))
  - name: kubo-windows
    version: ((kubo-windows-version))

stemcells:
  - alias: linux
    os: ubuntu-xenial
    version: "621.55" #https://github.com/pivotal-cf/p-pks-integrations/blob/master/dependencies.yml TODO read from this repo to load latest stemcell
  - alias: windows
    os: windows2019
    version: "2019.19" #https://github.com/pivotal-cf/p-pks-integrations/blob/master/dependencies.yml TODO read from this repo to load latest stemcell

update:
  canaries: 1
  max_in_flight: 1
  # both watch times are in milliseconds
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
  - name: print-version-linux-ig
    azs:
      - ((first-az))
    instances: 1

    # IMPORTANT: for a VM with a single job, that job needs to be a default "service" rather than an errand,
    # since only a service implies that the VM needs to persist. So if we uncomment "lifecycle: errand", the VM gets destroyed by BOSH right after it is created.
    # lifecycle: errand
    jobs:
      - name: print-component-version
        release: kubo
    vm_type: micro
    stemcell: linux
    # in megabytes
    persistent_disk: 5120
    networks:
      - name: ((network-name))
  - name: print-version-windows-ig
    azs:
      - ((first-az))
    instances: 1

    jobs:
      - name: print-kubo-windows-component-version
        release: kubo-windows
    # we need a root disk size of at least 32gigs or else we will not be able to start
    # see other options via:
    # bosh int <(bosh cloud-config) --path /vm_types
    vm_type: medium.disk
    stemcell: windows
    networks:
      - name: ((network-name))
addons: []
