---
resource_types:
- name: github-release-with-version-filtering
  type: docker-image
  source:
    repository: pcfkubo/github-release-resource
    tag: filter-version

- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: s3-kubernetes-common-core-linux
  type: s3
  source:
    bucket: "essentialpks-staging"
    regexp: "vmware-tanzu-kubernetes-grid/523a448aa3e9a0ef93ff892dceefee0a/kubernetes-binary-v(1.13.\\d*).*.tar.gz"
    region_name: "us-west-2"

- name: git-pks-kubo-release
  type: git
  source:
    uri: git@github.com:pivotal-cf/pks-kubo-release.git
    branch: 1.4.x
    private_key: ((git-ssh-key.private_key))

- name: git-pks-kubo-release-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/pks-kubo-release.git
    branch: master
    private_key: ((git-ssh-key.private_key))

jobs:
- name: bump-k8s-in-pks-kubo-release
  plan:
  - in_parallel:
    - get: git-pks-kubo-release
    - get: git-pks-kubo-release-ci
    - get: s3-kubernetes-common-core-linux
      trigger: true
  - task: bump-k8s-in-pks-kubo-release
    config: &config
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: stable
      run:
        path: git-pks-kubo-release-ci/ci/scripts/bump-k8s.sh
      inputs:
        - name: git-pks-kubo-release
        - name: git-pks-kubo-release-ci
        - name: s3-kubernetes-common-core-linux
      params:
        ACCESS_KEY_ID: ((gcs-access-key-id))
        SECRET_ACCESS_KEY: ((gcs-secret-access-key))
        CFCR_USER_TOKEN: ((cfcr-git-user-token))
        GIT_SSH_KEY: |
          ((git-ssh-key.private_key))
