---
resource_types:
- name: github-release-with-version-filtering
  type: docker-image
  source:
    repository: pcfkubo/github-release-resource
    tag: filter-version

- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: k8s-release
  type: github-release-with-version-filtering
  source:
    owner: kubernetes
    repository: kubernetes
    # only patches get updated
    version_filter: "< 1.16.0"

- name: gcs-kubernetes-windows
  type: gcs-resource
  source:
      bucket: "kubernetes-release"
      json_key: ((gcs-json-key))
      regexp: "release/v(1.15.\\d*)/bin/windows/amd64/kube-proxy.exe"

- name: git-pks-kubernetes-release
  type: git
  source:
    uri: git@github.com:pivotal-cf/pks-kubernetes-release.git
    branch: 1.6.x
    private_key: ((git-ssh-key.private_key))

- name: git-pks-kubernetes-release-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/pks-kubernetes-release.git
    branch: main
    private_key: ((git-ssh-key.private_key))

- name: git-pks-kubernetes-windows-release
  type: git
  source:
    uri: git@github.com:pivotal-cf/pks-kubernetes-windows-release.git
    branch: 1.6.x
    private_key: ((git-ssh-key.private_key))

jobs:
- name: bump-k8s-in-pks-kubo-release
  plan:
  - in_parallel:
    - get: git-pks-kubernetes-release
    - get: git-pks-kubernetes-release-ci
    - get: k8s-release
      trigger: true
  - task: bump-k8s-in-pks-kubernetes-release
    config: &config
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: odpks/pks-ci
      run:
        path: git-pks-kubernetes-release-ci/ci/scripts/bump-k8s.sh
      inputs:
        - name: git-pks-kubernetes-release
        - name: git-pks-kubernetes-release-ci
        - name: k8s-release
      params:
        BASE_BRANCH: 1.6.x
        BINARY_DIRECTORY: k8s-release
        BUMP_DOCKER: false
        USE_COMMON_CORE: false
        GCS_JSON_KEY: ((gcs-bosh-blobstore-json-key))
        GIT_USER_TOKEN: ((git-write-token))
        GIT_SSH_KEY: |
          ((git-ssh-key.private_key))

- name: bump-k8s-in-pks-kubo-release-windows
  plan:
    - in_parallel:
        - get: git-pks-kubernetes-release-ci
        - get: git-pks-kubernetes-windows-release
        - get: gcs-kubernetes-windows
          trigger: true
    - task: bump-k8s-in-pks-kubernetes-windows-release
      config:
        <<: *config
        run:
          path: git-pks-kubernetes-release-ci/ci/scripts/bump-k8s.sh
        inputs:
          - name: git-pks-kubernetes-release-ci
          - name: git-pks-kubernetes-windows-release
          - name: gcs-kubernetes-windows
        params:
          BASE_BRANCH: 1.6.x
          BINARY_DIRECTORY: gcs-kubernetes-windows
          BUMP_DOCKER: false
          REPO: windows
          GCS_JSON_KEY: ((gcs-bosh-blobstore-json-key))
          GIT_USER_TOKEN: ((git-write-token))
          GIT_SSH_KEY: |
            ((git-ssh-key.private_key))
