# Apply me with this command:
# 1) be inside CI folder
# 2) ./set_pipeline bump-docker-for-pks-1.8

resource_types:
  - name: github-release-with-version-filtering
    type: docker-image
    source:
      repository: pcfkubo/github-release-resource
      tag: filter-version


resources:
  - name: git-pks-docker-boshrelease
    type: git
    source:
      uri: git@github.com:pivotal-cf/pks-docker-boshrelease
      branch: bump-prep
      private_key: ((pks-bot-ssh-key.private_key))

  - name: git-docker-ce-release
    type: github-release-with-version-filtering
    source:
      owner: docker
      repository: docker-ce
      version_filter: "< 19.03.6"
      access_token: ((git-write-token))

  - name: git-pks-kubo-release-ci
    type: git
    source:
      uri: git@github.com:pivotal-cf/pks-kubo-release.git
      branch: feature/bump-docker
      private_key: ((pks-bot-ssh-key.private_key))
      paths: [ci]

  - name: git-pks-kubo-release-windows
      type: git
      source:
        uri: git@github.com:pivotal-cf/pks-kubo-release-windows
        branch: master
        private_key: ((pks-bot-ssh-key.private_key))

jobs:
  - name: bump-docker-in-pks-kubo-release
    plan:
      - in_parallel:
          - get: git-pks-docker-boshrelease
          - get: git-pks-kubo-release-ci
          - get: git-docker-ce-release
            trigger: true
      - task: bump-docker-in-pks-kubo-release
        config: &config
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: odpks/pks-ci
          run:
            path: git-pks-kubo-release-ci/ci/scripts/bump-docker.sh
          inputs:
            - name: git-pks-docker-boshrelease
            - name: git-pks-kubo-release-ci
            - name: git-docker-ce-release
          params:
            BASE_BRANCH: master
            BLOBSTORE_GCS_JSON_KEY: ((gcs-bosh-blobstore-json-key))
            BINARY_DIRECTORY: git-docker-ce-release
            CFCR_USER_TOKEN: ((git-write-token))
            GIT_SSH_KEY: |
              ((pks-bot-ssh-key.private_key))
  - name: bump-docker-in-pks-kubo-release-windows
    plan:
      - in_parallel:
        - get: git-pks-kubo-release-windows
        - get: git-pks-kubo-release-ci
        - get: git-docker-ce-release
          trigger: true
        - task: bump-docker-in-pks-kubo-release-windows
          config: &config
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: odpks/pks-ci
            run:
              path: git-pks-kubo-release-ci/ci/scripts/bump-docker.sh
            inputs:
              - name: git-pks-kubo-release-windows
              - name: git-pks-kubo-release-ci
              - name: git-docker-ce-release
            params:
              BASE_BRANCH: master
              BLOBSTORE_GCS_JSON_KEY: ((gcs-bosh-blobstore-json-key))
              BINARY_DIRECTORY: git-docker-ce-release
              CFCR_USER_TOKEN: ((git-write-token))
              GIT_SSH_KEY: |
                ((pks-bot-ssh-key.private_key))
