---
resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource
    tag: latest

resources:
- name: pool-pks-locks
  type: pool
  source:
    uri: git@github.com:pivotal-cf/pks-locks.git
    pool: gcp-flannel-om25-terraform
    branch: master
    private_key: ((pks-bot-ssh-key.private_key))

- name: git-kubo-odb-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/kubo-odb-ci
    branch: master
    private_key: ((pks-bot-ssh-key.private_key))

- name: gcs-pks-kubo-release
  type: gcs
  source:
    bucket: pipeline-store
    json_key: ((gcs-json-key))
    regexp: 1.6.x/cfcr/kubo-release-(\d+.*).tgz
- name: gcs-pks-kubo-release-windows
  type: gcs
  source:
    bucket: pipeline-store
    json_key: ((gcs-json-key))
    regexp: 1.6.x/cfcr/kubo-release-windows-(.*).tgz

# redeclare the same git resource to isolate the CI as something that can rapidly change
# without triggering or requiring passed
- name: git-boshcycle-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/pks-kubo-release.git
    branch: osl-pipeline
    private_key: ((git-ssh-key.private_key))
    paths: [ci]

jobs:
- name: claim-lock
  max_in_flight: 1
  plan:
  - in_parallel:
    - get: git-kubo-odb-ci
# add trigger:true back when we get a [slack] notification on failure, and agree to monitor env use as a team
#      trigger: true
    - get: gcs-pks-kubo-release
#      trigger: true
    - get: gcs-pks-kubo-release-windows
#      trigger: true
    - get: pool-pks-locks
  - put: pool-pks-locks
    params:
      acquire: true

- name: upload-kubo-release
  plan:
    - in_parallel:
        - get: git-kubo-odb-ci
        - get: git-boshcycle-ci
        - get: gcs-pks-kubo-release
        - get: pool-pks-locks
          trigger: true
          passed: [ 'claim-lock' ]
    - task: create-bosh-config
      tags: ['gcp']
      input_mapping:
        locks-repo: pool-pks-locks
      file: git-kubo-odb-ci/tasks/create-bosh-config.yml
    - task: upload-kubo-release
      privileged: true
      file: git-boshcycle-ci/ci/utils/upload-kubo-release.yml

- name: upload-kubo-release-windows
  plan:
    - in_parallel:
        - get: git-kubo-odb-ci
        - get: git-boshcycle-ci
        - get: pool-pks-locks
          trigger: true
          passed: [ 'claim-lock' ]
        - get: gcs-pks-kubo-release-windows
          passed: [ 'claim-lock' ]
    - task: create-bosh-config
      tags: ['gcp']
      input_mapping:
        locks-repo: pool-pks-locks
      file: git-kubo-odb-ci/tasks/create-bosh-config.yml
    - task: upload-kubo-release-windows
      privileged: true
      file: git-boshcycle-ci/ci/utils/upload-kubo-release-windows.yml

- name: deploy-manifest
  plan:
  - in_parallel:
    - get: git-kubo-odb-ci
    - get: git-boshcycle-ci
    - get: pool-pks-locks
      trigger: true
      passed: [ 'claim-lock' ]
    - get: gcs-pks-kubo-release
    - get: gcs-pks-kubo-release-windows
  - task: create-bosh-config
    tags: ['gcp']
    input_mapping:
      locks-repo: pool-pks-locks
    file: git-kubo-odb-ci/tasks/create-bosh-config.yml
  - task: deploy-release
    privileged: true
    file: git-boshcycle-ci/ci/open-source-management/deploy-manifest.yml

- name: generate-osm
  plan:
  - in_parallel:
    - get: git-kubo-odb-ci
    - get: git-boshcycle-ci
    - get: pool-pks-locks
      trigger: true
      passed: [ 'deploy-manifest' ]
    - get: gcs-pks-kubo-release
      passed: [ 'deploy-manifest' ]
    - get: gcs-pks-kubo-release-windows
      passed: [ 'deploy-manifest' ]
  - task: create-bosh-config
    tags: ['gcp']
    input_mapping:
      locks-repo: pool-pks-locks
    file: git-kubo-odb-ci/tasks/create-bosh-config.yml
  - task: run-tests
    privileged: true
    file: git-boshcycle-ci/ci/open-source-management/generate-osm.yml

- name: cleanup
  plan:
  - in_parallel:
    - get: git-kubo-odb-ci
    - get: git-boshcycle-ci
    - get: pool-pks-locks
      trigger: true
      passed: [ 'generate-osm' ]
    - get: gcs-pks-kubo-release
      passed: [ 'generate-osm' ]
    - get: gcs-pks-kubo-release-windows
      passed: [ 'generate-osm' ]
  - task: create-bosh-config
    tags: ['gcp']
    input_mapping:
      locks-repo: pool-pks-locks
    file: git-kubo-odb-ci/tasks/create-bosh-config.yml
  - task: delete-release
    privileged: true
    file: git-boshcycle-ci/ci/open-source-management/cleanup.yml
  - put: pool-pks-locks
    params:
      release: pool-pks-locks
