---
resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource
    tag: latest

resources:
- name: pool-pks-locks
  type: pool
  source:
    uri: git@github.com:pivotal-cf/pks-locks.git
    pool: gcp-flannel-om26-terraform
    branch: master
    private_key: ((git-ssh-key.private_key))

- name: git-kubo-odb-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/kubo-odb-ci
    branch: master
    private_key: ((git-ssh-key.private_key))

- name: git-pks-kubernetes-release
  type: git
  source:
    uri: git@github.com:pivotal-cf/pks-kubernetes-release.git
    branch: 1.8.x
    private_key: ((git-ssh-key.private_key))
    disable_ci_skip: true
    paths: 
    - "releases/kubo/kubo-1.8*.yml"

- name: git-pks-kubernetes-windows-release
  type: git
  source:
    uri: git@github.com:pivotal-cf/pks-kubernetes-windows-release.git
    branch: 1.8.x
    private_key: ((git-ssh-key.private_key))
    disable_ci_skip: true
    paths: 
    - "releases/kubo-windows/kubo-windows-1.8*.yml"


# redeclare the same git resource to isolate the CI as something that can rapidly change
# without triggering or requiring passed
- name: git-pks-kubernetes-release-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/pks-kubernetes-release.git
    branch: osl-pipeline
    private_key: ((git-ssh-key.private_key))
    paths: [ci]

- name: linux-stemcell
  source:
    name: bosh-google-kvm-ubuntu-xenial-go_agent
    version_family: "621.55"
  type: bosh-io-stemcell

- name: windows-stemcell
  source:
    name: bosh-google-kvm-windows2019-go_agent
    version_family: "2019.19"
  type: bosh-io-stemcell

jobs:
- name: claim-lock
  max_in_flight: 1
  plan:
  - in_parallel:
    - get: git-kubo-odb-ci
    - get: git-pks-kubernetes-release
      trigger: true
    - get: git-pks-kubernetes-windows-release
      trigger: true
    - get: pool-pks-locks
  - put: pool-pks-locks
    params:
      acquire: true

- name: deploy-manifest
  plan:
  - in_parallel:
    - get: git-kubo-odb-ci
    - get: pool-pks-locks
      passed:
        - 'claim-lock'    
    - get: git-pks-kubernetes-release
      trigger: true
      passed: [ 'claim-lock' ]
    - get: git-pks-kubernetes-windows-release
      trigger: true
      passed: [ 'claim-lock' ]
    - get: git-pks-kubernetes-release-ci
    - get: linux-stemcell
    - get: windows-stemcell
  - task: create-bosh-config
    tags: ['gcp']
    input_mapping:
      locks-repo: pool-pks-locks
    file: git-kubo-odb-ci/tasks/create-bosh-config.yml
  - task: upload-linux-stemcell
    privileged: true
    input_mapping:
      stemcell: linux-stemcell
    file: git-pks-kubernetes-release-ci/ci/minimum-release-verification/upload-stemcell/task.yml
  - task: upload-windows-stemcell
    privileged: true
    input_mapping:
      stemcell: windows-stemcell
    file: git-pks-kubernetes-release-ci/ci/minimum-release-verification/upload-stemcell/task.yml
  - task: config-blobstore
    file: git-pks-kubernetes-release-ci/ci/tasks/config-blobstore/task.yml
    params:
      ACCESS_KEY_ID: ((gcs-access-key-id))
      SECRET_ACCESS_KEY: ((gcs-secret-access-key))

  - task: deploy-release
    privileged: true
    file: git-pks-kubernetes-release-ci/ci/open-source-management/deploy-manifest.yml
    params:
      VERSION: "1.8"

- name: generate-osm
  plan:
  - in_parallel:
    - get: git-kubo-odb-ci
    - get: git-pks-kubernetes-release-ci
    - get: pool-pks-locks
      passed: [ 'deploy-manifest' ]
    - get: git-pks-kubernetes-release
      trigger: true
      passed: [ 'deploy-manifest' ]
    - get: git-pks-kubernetes-windows-release
      trigger: true
      passed: [ 'deploy-manifest' ]
  - task: create-bosh-config
    tags: ['gcp']
    input_mapping:
      locks-repo: pool-pks-locks
    file: git-kubo-odb-ci/tasks/create-bosh-config.yml
  - task: run-tests
    privileged: true
    file: git-pks-kubernetes-release-ci/ci/open-source-management/generate-osm.yml

- name: cleanup
  plan:
  - in_parallel:
    - get: git-kubo-odb-ci
    - get: git-pks-kubernetes-release-ci
    - get: pool-pks-locks
      trigger: true
      passed: [ 'generate-osm' ]
    - get: git-pks-kubernetes-release
      passed: [ 'generate-osm' ]
    - get: git-pks-kubernetes-windows-release
      passed: [ 'generate-osm' ]
  - task: create-bosh-config
    tags: ['gcp']
    input_mapping:
      locks-repo: pool-pks-locks
    file: git-kubo-odb-ci/tasks/create-bosh-config.yml
  - task: delete-release
    privileged: true
    file: git-pks-kubernetes-release-ci/ci/open-source-management/cleanup.yml
  - put: pool-pks-locks
    params:
      release: pool-pks-locks
